import AppHeader from "@/components/AppHeader.js";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NewHeader from "@/components/AppHeader.js/newHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <AppHeader /> */}
      <NewHeader />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
